### ISSUE TITLE
Deis builder fails to start on kubernetes 1.3

### ISSUE THREAD

**Issue by felipejfc** [deis/builder#381] opened 2016-07-06 01:58 UTC
it keeps crashing with this error:

2016/07/05 21:51:27 Error getting storage parameters (read /var/run/secrets/deis/objectstore/creds/..7987_05_07_21_24_58.289604052: is a directory)

**Comment by bacongobbler** [comment] 2016-07-06 02:28
this looks like a duplicate of #379. I'll see if I can find an upstream issue for this.

**Closed** 2016-07-06 02:34 UTC
