### ISSUE TITLE
slugbuilder and dockerbuilder should be jobs rather pods

### ISSUE THREAD

**Issue by smothiki** [deis/builder#63] opened 2015-12-18 22:09 UTC
change kind of manifest to job instead of pod.
If kind is pod then slugbuilder and dockerbuilder will leave in error state.

**Comment by arschles** [comment] 2015-12-18 23:29
Duplicate of https://github.com/deis/builder/issues/57. Appending this issue there and closing

**Closed by arschles** 2015-12-18 23:29 UTC
