### ISSUE TITLE
Builder v2.6 cannot work with env variables

### ISSUE THREAD

**Issue by ineu** [deis/builder#455] opened 2016-12-09 12:37 UTC
Given the config:
```
=== test Config
FOO      bar
```
In Deis 2.9 with builder 2.6.1 (and 2.6.0)
```
> $ kd set image deploy/deis-builder deis-builder=quay.io/deis/builder:v2.6.0
...
> $ gp deis HEAD:master
Подсчет объектов: 12, готово.
Delta compression using up to 8 threads.
Сжатие объектов: 100% (9/9), готово.
Запись объектов: 100% (12/12), 1.08 KiB | 0 bytes/s, готово.
Total 12 (delta 3), reused 0 (delta 0)
remote: 2016/12/09 12:32:44 Error running git receive hook [error creating/updating secret test-build-env: (Secret "test-build-env" is invalid: data[FOO]: Invalid value: "FOO": must have at most 253 characters and match regex \.?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)]
```

If I go back to 2.5.5, everything is back to normal:
```
> $ kd set image deploy/deis-builder deis-builder=quay.io/deis/builder:v2.5.5
...
> $ gp deis HEAD:master
Подсчет объектов: 12, готово.
Delta compression using up to 8 threads.
Сжатие объектов: 100% (9/9), готово.
Запись объектов: 100% (12/12), 1.08 KiB | 0 bytes/s, готово.
Total 12 (delta 3), reused 0 (delta 0)
Starting build... but first, coffee!
-----> Restoring cache...
       Done!
-----> Ruby app detected
-----> Compiling Ruby/Rack
...
```

**Comment by bacongobbler** [comment] 2016-12-09 15:19
I think this is due to running an older version of k8s. Can you try again with k8s v1.3.10?

**Comment by ineu** [comment] 2016-12-09 15:48
Sure, will try

**Comment by felixbuenemann** [comment] 2016-12-09 16:25
I think this is caused by #444.

**Comment by ineu** [comment] 2016-12-10 09:25
Tried a fresh install on the 
```
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:42:39Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```
Now I have the https://github.com/deis/builder/issues/454 issue

**Comment by ineu** [comment] 2016-12-10 09:40
With the fix from https://github.com/deis/builder/issues/454#issuecomment-265340858 deploy works with the builder v2.6.1. So it's either the fresh installation which helped or the 1.4 kube version

**Comment by kmala** [comment] 2016-12-14 21:24
fixed in https://github.com/deis/slugbuilder/pull/126

**Closed by kmala** 2016-12-14 21:24 UTC
