### ISSUE TITLE
create a client for the Deis controller

### ISSUE THREAD

**Issue by arschles** [deis/builder#82] opened 2016-01-06 00:13 UTC
#72 introduces some duplicated code to talk with the Deis controller. This issue is for refactoring all of it into a common controller client. Create a new `github.com/deis/builder/pkg/controller` package and put the client in there

**Comment by bacongobbler** [comment] 2016-01-06 00:26
is https://github.com/deis/workflow/tree/master/client/controller insufficient for the job at hand?

**Comment by arschles** [comment] 2016-01-06 00:31
Yes, looks like it will be, thanks!

My only concern is that it looks to be pulling in a [lot of dependencies](https://github.com/deis/workflow/blob/master/client/glide.lock). I'd like to avoid that (see #75), but I'll try it and see how much bloat it adds.

**Comment by helgi** [comment] 2016-01-06 00:34
Can it be extracted out and make `client` and `builder` share it?

**Comment by arschles** [comment] 2016-01-06 00:58
Yes, I'll pursue that path when I come to this issue.

**Comment by technosophos** [comment] 2016-02-22 20:21
I am pulling this off of the beta list since it is not required for Beta to ship.

**Comment by Joshua-Anderson** [comment] 2016-07-21 19:57
Is this a dupe of #90 (or vice versa)?

**Comment by Joshua-Anderson** [comment] 2016-08-02 20:07
Now that a client for the deis controller exists in controller-sdk-go, I'm going to close this in favor of #90 which is updating the builder to use the client.

**Closed by Joshua-Anderson** 2016-08-02 20:07 UTC
Labels: enhancement, in progress
