### ISSUE TITLE
Proposal feat(builder): use env vars to define images to use

### ISSUE THREAD

**Issue by aledbf** [deis/builder#219] opened 2016-03-02 16:33 UTC
Right now the name of the images are defined in [go](https://github.com/deis/builder/blob/master/pkg/gitreceive/k8s_util.go#L16) so the only way to change this is to fork and build a custom image.

**Comment by bacongobbler** [comment] 2016-03-02 16:35
dupe of #66

**Closed by bacongobbler** 2016-03-02 16:35 UTC
Labels: proposal
